<?xml version="1.0" encoding="utf-8"?>
<Project>

    <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <ArtifactsPath>$(SolutionDirectory).artifacts/src</ArtifactsPath>
        <Copyright>Copyright © 2024 Christopher Whitley</Copyright>
        <Authors>Christopher Whitley and contributors</Authors>
        <Company>Aristurtle</Company>
        <PackageProjectUrl>https://github.com/AristurtleDev/AsepriteDotNet</PackageProjectUrl>
        <PackageIcon>nuget-icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes></PackageReleaseNotes>
        <PackageTags>Aseprite;reader;pixel art;png;spritesheet;tilesheet</PackageTags>
        <RepositoryType>git</RepositoryType>
        <RepositoryBranch>main</RepositoryBranch>
        <RepositoryUrl>https://github.com/AristurtleDev/AsepriteDotNet</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>

</Project>
